# Generated by Django 2.1 on 2019-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
