# Generated by Django 2.1 on 2019-04-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0003_auto_20190415_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='entity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='practices.Entity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='practice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='practices.Practice'),
        ),
    ]
