# Generated by Django 2.1 on 2019-04-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0004_auto_20190415_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='practice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='practices.Practice'),
        ),
    ]
